### PR TITLE
Hof-17: Update hof package to 17

### PR DESCRIPTION
**Pull request by sulthan-ahmed**
## What?
Update the generator to install hof 17, which is the latest
## Why?
Because it was installing 12 and that is ancient mate

## Anything Else?
* I wasn't able to test it but I'm sure it will work but no production issues if it fails
* Perhaps, it's should just install the latest one but out of scope for this PR. 
* I've not added a JIRA ticket because it seems unnecessary

### CODE REVIEW

**Review by AlexFranklinHODDaT — COMMENTED** [review]
Should we update the version of hof-generator in the top level package.json, so we can tag and publish with the updated version number?

**Comment by sulthan-ahmed** [comment]
can do if you like

there is also this way too i think that works
```
* `git checkout master`
* `get pull origin master`
* `npm version major|minor|patch` 
(major = breaking, minor non-breaking but more than a patch, like a new feature, a la this. patch = non breaking usually a bugfix).  This creates a version update in your local commit, which you can view if you do git log
* `git push origin master --tags`
* `npm publish`
```

**Comment by sulthan-ahmed** [comment]
that way might not work now I added protection to all master branches in hof tbh

**Comment by sulthan-ahmed** [comment]
let me try it in the branch instead

**Review by AlexFranklinHODDaT — APPROVED** [review]

**Comment by AlexFranklinHODDaT** [comment]
@sulthan-ahmed the travis ci checks are failing for node 8. From the logs looks like might need to update the version of bluebird.

**Comment by sulthan-ahmed** [comment]
forget node 8, it's ancient :) we need to sort out our CI tbh

**Pull request merged**
