### PR TITLE
Implement generator

### PR DESCRIPTION
**Pull request by lennym**
Installs a binary with two commands: 

* `init` - creates a new top-level hof app in an empty directory
* `app` - creates a new app in an existing implementation - e.g. creates a dir in `./apps`

### CODE REVIEW

**Comment by joefitter** [comment]
Looks ace! Only thing I can see missing is the addition of a common directory, but probably out of scope for the generator.

Also step.html isn't needed as in included in hof-template-partials. Or is this just here as an example?

**Comment by easternbloc** [comment]
Squash and Merge? :trollface:

**Comment by lennym** [comment]
@joefitter Yeah, common directories are not necessary, and I thought could be confusing when most use cases are probably single apps.

**Comment by lennym** [comment]
@joefitter Yeah, that file is there because

a) if there's not *some file* there then `views` directory doesn't get created and bootstrap freaks out. This should arguably be fixed at bootstrap.
b) there's a close to 100% chance that the user is going to want that directory to exist at some point, so it's best to create it for them.

**Comment by easternbloc** [comment]
a) yes.

**Comment by joefitter** [comment]
a) @JoeChapman didn't you fix this?

**Comment by lennym** [comment]
a) it's not fixed in the latest version. There was a change that made the *global* views directory optional, but the *app* views directory still needs to exist. bootstrap throws if the defined path does not exist here: https://github.com/UKHomeOfficeForms/hof-bootstrap/blob/master/lib/helpers.js#L27-L33 and defaults the path to `app/:name/views` here: https://github.com/UKHomeOfficeForms/hof-bootstrap/blob/master/lib/helpers.js#L8-L10

**Pull request merged**
